version: '3.8'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      #      - ./sql-scripts:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
    networks:
      - nginxnetwork
  main:
    container_name: main
    image: main
    command: cross-env pm2 start ecosystem.config.js --no-daemon
    ports:
      - 5000:5000
    networks:
      - nginxnetwork
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./tools/default-dev.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
    networks:
      - nginxnetwork
networks:
  nginxnetwork:
    name: nginxnetwork
    driver: bridge
